/* LES 400 STYLES DU MODELE, RAMENES A L'ATLAS SONAA.
 *
 * Le modele de reconnaissance rend 400 etiquettes Discogs de la forme
 * « Electronic---Deep House ». L'atlas SONAA connait 219 genres repartis en
 * 14 familles. Les deux taxonomies ne se recouvrent pas : Discogs couvre
 * toute la musique enregistree, SONAA ne couvre que l'electronique, et le
 * decoupe beaucoup plus finement.
 *
 * CETTE TABLE EST ECRITE A LA MAIN, ET C'EST VOULU. Un rapprochement
 * automatique par nom aurait donne « Electronic---Latin » vers le genre
 * latinfreestyle, « Electronic---Tribal » vers rien, et « Funk / Soul---Disco »
 * vers rien non plus alors que SONAA a un genre disco. Les 400 lignes sont
 * relues une par une, et le test verifie seulement ce qu'une machine peut
 * verifier : que chaque identifiant cite existe dans le corpus.
 *
 * TROIS CAS, ET LE CHAMP `famille` CHANGE DE SENS AVEC EUX.
 *
 * 1. Le style a un equivalent exact : `sonaa` porte l'identifiant du genre,
 *    `famille` porte sa famille SONAA. La fiche du genre est ouvrable.
 * 2. Le style est electronique mais trop large ou absent de l'atlas, par
 *    exemple « House » tout court ou « Chiptune » : `sonaa` vaut null et
 *    `famille` porte quand meme une famille SONAA, vers laquelle on peut
 *    envoyer le lecteur. Dix-neuf styles sont dans ce cas.
 * 3. Le style n'est pas electronique, de « Rock---Grunge » a « Jazz---Bop » :
 *    `sonaa` vaut null et `famille` porte le nom de la famille DISCOGS, pour
 *    l'affichage seulement. Il n'y a rien a ouvrir, et c'est normal : le
 *    modele a raison de dire que ce n'est pas de l'electronique.
 *
 * `familleSonaa()` est la seule facon correcte de distinguer 2 de 3 : elle
 * rend l'identifiant quand la famille en est une chez nous, null sinon. */

import { FAMILIES } from '../atlas/structures.ts';

export interface StyleReconnu {
  /** L'etiquette rendue par le modele, telle quelle. */
  readonly discogs: string;
  /** L'identifiant du genre dans le corpus SONAA, ou null. */
  readonly sonaa: string | null;
  /** Une famille SONAA quand le style est electronique, le nom de la famille
      Discogs sinon. Voir l'en-tete. */
  readonly famille: string;
}

/** La famille SONAA d'une entree, ou null quand `famille` porte un nom de
    famille Discogs et ne designe donc rien d'ouvrable chez nous. */
export function familleSonaa(entree: StyleReconnu): string | null {
  return FAMILIES.some((f) => f.id === entree.famille) ? entree.famille : null;
}

/** Le style, sans son prefixe de famille : « Electronic---Deep House » rend
    « Deep House ». C'est ce qu'on affiche. */
export function nomCourt(discogs: string): string {
  const coupe = discogs.indexOf('---');
  return coupe === -1 ? discogs : discogs.slice(coupe + 3);
}

export const STYLES_RECONNUS: readonly StyleReconnu[] = [
  { discogs: "Blues---Boogie Woogie", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Chicago Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Country Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Delta Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Electric Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Harmonica Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Jump Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Louisiana Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Modern Electric Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Piano Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Rhythm & Blues", sonaa: null, famille: "Blues" },
  { discogs: "Blues---Texas Blues", sonaa: null, famille: "Blues" },
  { discogs: "Children's---Educational", sonaa: null, famille: "Children's" },
  { discogs: "Children's---Nursery Rhymes", sonaa: null, famille: "Children's" },
  { discogs: "Children's---Story", sonaa: null, famille: "Children's" },
  { discogs: "Classical---Baroque", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Choral", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Classical", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Contemporary", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Impressionist", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Medieval", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Modern", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Neo-Classical", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Neo-Romantic", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Opera", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Post-Modern", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Renaissance", sonaa: null, famille: "Classical" },
  { discogs: "Classical---Romantic", sonaa: null, famille: "Classical" },
  { discogs: "Electronic---Abstract", sonaa: null, famille: "ambient" },
  { discogs: "Electronic---Acid", sonaa: "acidhouse", famille: "house" },
  { discogs: "Electronic---Acid House", sonaa: "acidhouse", famille: "house" },
  { discogs: "Electronic---Acid Jazz", sonaa: "nujazz", famille: "downtempo" },
  { discogs: "Electronic---Ambient", sonaa: "ambientgenre", famille: "ambient" },
  { discogs: "Electronic---Bassline", sonaa: "bassline", famille: "bass" },
  { discogs: "Electronic---Beatdown", sonaa: "usdeephouse", famille: "house" },
  { discogs: "Electronic---Berlin-School", sonaa: "kosmische", famille: "roots" },
  { discogs: "Electronic---Big Beat", sonaa: "bigbeat", famille: "breaks" },
  { discogs: "Electronic---Bleep", sonaa: "bleeptechno", famille: "techno" },
  { discogs: "Electronic---Breakbeat", sonaa: "breakbeat", famille: "breaks" },
  { discogs: "Electronic---Breakcore", sonaa: "breakcore", famille: "breaks" },
  { discogs: "Electronic---Breaks", sonaa: "nuskoolbreaks", famille: "breaks" },
  { discogs: "Electronic---Broken Beat", sonaa: "brokenbeat", famille: "breaks" },
  { discogs: "Electronic---Chillwave", sonaa: "chillwave", famille: "downtempo" },
  { discogs: "Electronic---Chiptune", sonaa: null, famille: "ambient" },
  { discogs: "Electronic---Dance-pop", sonaa: null, famille: "disco" },
  { discogs: "Electronic---Dark Ambient", sonaa: "darkambient", famille: "ambient" },
  { discogs: "Electronic---Darkwave", sonaa: "darkwave", famille: "industrial" },
  { discogs: "Electronic---Deep House", sonaa: "usdeephouse", famille: "house" },
  { discogs: "Electronic---Deep Techno", sonaa: "hypnotictechno", famille: "techno" },
  { discogs: "Electronic---Disco", sonaa: "disco", famille: "disco" },
  { discogs: "Electronic---Disco Polo", sonaa: null, famille: "disco" },
  { discogs: "Electronic---Donk", sonaa: "bouncytechno", famille: "hardcore" },
  { discogs: "Electronic---Downtempo", sonaa: "downtempogenre", famille: "downtempo" },
  { discogs: "Electronic---Drone", sonaa: "drone", famille: "ambient" },
  { discogs: "Electronic---Drum n Bass", sonaa: "drumandbass", famille: "breaks" },
  { discogs: "Electronic---Dub", sonaa: "dub", famille: "roots" },
  { discogs: "Electronic---Dub Techno", sonaa: "dubtechno", famille: "techno" },
  { discogs: "Electronic---Dubstep", sonaa: "dubstep", famille: "bass" },
  { discogs: "Electronic---Dungeon Synth", sonaa: "dungeonsynth", famille: "ambient" },
  { discogs: "Electronic---EBM", sonaa: "ebm", famille: "industrial" },
  { discogs: "Electronic---Electro", sonaa: "electrofunk", famille: "electro" },
  { discogs: "Electronic---Electro House", sonaa: "electrohouse", famille: "house" },
  { discogs: "Electronic---Electroclash", sonaa: "electroclash", famille: "electro" },
  { discogs: "Electronic---Euro House", sonaa: null, famille: "house" },
  { discogs: "Electronic---Euro-Disco", sonaa: "eurodisco", famille: "disco" },
  { discogs: "Electronic---Eurobeat", sonaa: "hinrg", famille: "disco" },
  { discogs: "Electronic---Eurodance", sonaa: null, famille: "disco" },
  { discogs: "Electronic---Experimental", sonaa: null, famille: "ambient" },
  { discogs: "Electronic---Freestyle", sonaa: "freestyle", famille: "electro" },
  { discogs: "Electronic---Future Jazz", sonaa: "nujazz", famille: "downtempo" },
  { discogs: "Electronic---Gabber", sonaa: "gabber", famille: "hardcore" },
  { discogs: "Electronic---Garage House", sonaa: "garagehouse", famille: "house" },
  { discogs: "Electronic---Ghetto", sonaa: "ghettohouse", famille: "house" },
  { discogs: "Electronic---Ghetto House", sonaa: "ghettohouse", famille: "house" },
  { discogs: "Electronic---Glitch", sonaa: "glitch", famille: "ambient" },
  { discogs: "Electronic---Goa Trance", sonaa: "goatrance", famille: "psy" },
  { discogs: "Electronic---Grime", sonaa: "grime", famille: "bass" },
  { discogs: "Electronic---Halftime", sonaa: "drumandbass", famille: "breaks" },
  { discogs: "Electronic---Hands Up", sonaa: null, famille: "hardcore" },
  { discogs: "Electronic---Happy Hardcore", sonaa: "happyhardcore", famille: "hardcore" },
  { discogs: "Electronic---Hard House", sonaa: "hardhouse", famille: "house" },
  { discogs: "Electronic---Hard Techno", sonaa: "hardtechno", famille: "techno" },
  { discogs: "Electronic---Hard Trance", sonaa: "hardtrance", famille: "trance" },
  { discogs: "Electronic---Hardcore", sonaa: "hardcoretechno", famille: "hardcore" },
  { discogs: "Electronic---Hardstyle", sonaa: "hardstyle", famille: "hardcore" },
  { discogs: "Electronic---Hi NRG", sonaa: "hinrg", famille: "disco" },
  { discogs: "Electronic---Hip Hop", sonaa: "hiphop", famille: "roots" },
  { discogs: "Electronic---Hip-House", sonaa: "hiphouse", famille: "house" },
  { discogs: "Electronic---House", sonaa: null, famille: "house" },
  { discogs: "Electronic---IDM", sonaa: "idm", famille: "ambient" },
  { discogs: "Electronic---Illbient", sonaa: "illbient", famille: "ambient" },
  { discogs: "Electronic---Industrial", sonaa: "industrial", famille: "industrial" },
  { discogs: "Electronic---Italo House", sonaa: "italohouse", famille: "house" },
  { discogs: "Electronic---Italo-Disco", sonaa: "italodisco", famille: "disco" },
  { discogs: "Electronic---Italodance", sonaa: null, famille: "disco" },
  { discogs: "Electronic---Jazzdance", sonaa: "nujazz", famille: "downtempo" },
  { discogs: "Electronic---Juke", sonaa: "juke", famille: "house" },
  { discogs: "Electronic---Jumpstyle", sonaa: "jumpstyle", famille: "hardcore" },
  { discogs: "Electronic---Jungle", sonaa: "jungle", famille: "breaks" },
  { discogs: "Electronic---Latin", sonaa: "latinhouse", famille: "house" },
  { discogs: "Electronic---Leftfield", sonaa: null, famille: "ambient" },
  { discogs: "Electronic---Makina", sonaa: "makina", famille: "hardcore" },
  { discogs: "Electronic---Minimal", sonaa: "minimaltechno", famille: "minimal" },
  { discogs: "Electronic---Minimal Techno", sonaa: "minimaltechno", famille: "minimal" },
  { discogs: "Electronic---Modern Classical", sonaa: null, famille: "ambient" },
  { discogs: "Electronic---Musique Concrète", sonaa: "musiqueconcrete", famille: "roots" },
  { discogs: "Electronic---Neo Trance", sonaa: null, famille: "trance" },
  { discogs: "Electronic---Neofolk", sonaa: null, famille: "industrial" },
  { discogs: "Electronic---New Age", sonaa: "newage", famille: "ambient" },
  { discogs: "Electronic---New Beat", sonaa: "newbeat", famille: "industrial" },
  { discogs: "Electronic---New Wave", sonaa: null, famille: "industrial" },
  { discogs: "Electronic---Noise", sonaa: null, famille: "industrial" },
  { discogs: "Electronic---Nu-Disco", sonaa: "nudisco", famille: "disco" },
  { discogs: "Electronic---Power Electronics", sonaa: "powerelectronics", famille: "industrial" },
  { discogs: "Electronic---Progressive Breaks", sonaa: "progressivebreaks", famille: "breaks" },
  { discogs: "Electronic---Progressive House", sonaa: "progressivehouse", famille: "house" },
  { discogs: "Electronic---Progressive Trance", sonaa: "progressivetrance", famille: "trance" },
  { discogs: "Electronic---Psy-Trance", sonaa: "psychedelictrance", famille: "psy" },
  { discogs: "Electronic---Rhythmic Noise", sonaa: "rhythmicnoise", famille: "industrial" },
  { discogs: "Electronic---Schranz", sonaa: "schranz", famille: "techno" },
  { discogs: "Electronic---Sound Collage", sonaa: "musiqueconcrete", famille: "roots" },
  { discogs: "Electronic---Speed Garage", sonaa: "speedgarage", famille: "bass" },
  { discogs: "Electronic---Speedcore", sonaa: "speedcore", famille: "hardcore" },
  { discogs: "Electronic---Synth-pop", sonaa: "synthpop", famille: "roots" },
  { discogs: "Electronic---Synthwave", sonaa: null, famille: "electro" },
  { discogs: "Electronic---Tech House", sonaa: "techhouse", famille: "minimal" },
  { discogs: "Electronic---Tech Trance", sonaa: "techtrance", famille: "trance" },
  { discogs: "Electronic---Techno", sonaa: null, famille: "techno" },
  { discogs: "Electronic---Trance", sonaa: "trance", famille: "trance" },
  { discogs: "Electronic---Tribal", sonaa: "tribalhouse", famille: "house" },
  { discogs: "Electronic---Tribal House", sonaa: "tribalhouse", famille: "house" },
  { discogs: "Electronic---Trip Hop", sonaa: "triphop", famille: "downtempo" },
  { discogs: "Electronic---Tropical House", sonaa: null, famille: "house" },
  { discogs: "Electronic---UK Garage", sonaa: "ukgarage", famille: "bass" },
  { discogs: "Electronic---Vaporwave", sonaa: null, famille: "downtempo" },
  { discogs: "Folk, World, & Country---African", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Bluegrass", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Cajun", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Canzone Napoletana", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Celtic", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Country", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Fado", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Flamenco", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Gamelan", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Folk", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Gospel", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Hawaiian", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Highlife", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Hillbilly", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Hindustani", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Klezmer", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Honky Tonk", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Indian Classical", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Laïkó", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Nordic", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Pacific", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Polka", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Raï", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Romani", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Soukous", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Séga", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Volksmusik", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Zouk", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Folk, World, & Country---Éntekhno", sonaa: null, famille: "Folk, World, & Country" },
  { discogs: "Funk / Soul---Afrobeat", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Bayou Funk", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Boogie", sonaa: "boogie", famille: "disco" },
  { discogs: "Funk / Soul---Contemporary R&B", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Disco", sonaa: "disco", famille: "disco" },
  { discogs: "Funk / Soul---Free Funk", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Funk", sonaa: "funk", famille: "roots" },
  { discogs: "Funk / Soul---Gospel", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Neo Soul", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---New Jack Swing", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---P.Funk", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Psychedelic", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Rhythm & Blues", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Soul", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---Swingbeat", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Funk / Soul---UK Street Soul", sonaa: null, famille: "Funk / Soul" },
  { discogs: "Hip Hop---Bass Music", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Boom Bap", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Bounce", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Britcore", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Cloud Rap", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Conscious", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Crunk", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Cut-up/DJ", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---DJ Battle Tool", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Electro", sonaa: "electrofunk", famille: "electro" },
  { discogs: "Hip Hop---G-Funk", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Gangsta", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Grime", sonaa: "grime", famille: "bass" },
  { discogs: "Hip Hop---Hardcore Hip-Hop", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Horrorcore", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Instrumental", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Jazzy Hip-Hop", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Miami Bass", sonaa: "miamibass", famille: "electro" },
  { discogs: "Hip Hop---Pop Rap", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Ragga HipHop", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---RnB/Swing", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Screw", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Thug Rap", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Trap", sonaa: null, famille: "Hip Hop" },
  { discogs: "Hip Hop---Trip Hop", sonaa: "triphop", famille: "downtempo" },
  { discogs: "Hip Hop---Turntablism", sonaa: null, famille: "Hip Hop" },
  { discogs: "Jazz---Afro-Cuban Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Afrobeat", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Avant-garde Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Big Band", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Bop", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Bossa Nova", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Contemporary Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Cool Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Dixieland", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Easy Listening", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Free Improvisation", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Free Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Fusion", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Gypsy Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Hard Bop", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Jazz-Funk", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Jazz-Rock", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Latin Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Modal", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Post Bop", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Ragtime", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Smooth Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Soul-Jazz", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Space-Age", sonaa: null, famille: "Jazz" },
  { discogs: "Jazz---Swing", sonaa: null, famille: "Jazz" },
  { discogs: "Latin---Afro-Cuban", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Baião", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Batucada", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Beguine", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Bolero", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Boogaloo", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Bossanova", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Cha-Cha", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Charanga", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Compas", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Cubano", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Cumbia", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Descarga", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Forró", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Guaguancó", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Guajira", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Guaracha", sonaa: null, famille: "Latin" },
  { discogs: "Latin---MPB", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Mambo", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Mariachi", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Merengue", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Nueva Cancion", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Pachanga", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Porro", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Ranchera", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Reggaeton", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Rumba", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Salsa", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Samba", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Son", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Son Montuno", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Tango", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Tejano", sonaa: null, famille: "Latin" },
  { discogs: "Latin---Vallenato", sonaa: null, famille: "Latin" },
  { discogs: "Non-Music---Comedy", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Dialogue", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Education", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Field Recording", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Interview", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Monolog", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Poetry", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Political", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Promotional", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Radioplay", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Religious", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Spoken Word", sonaa: null, famille: "Non-Music" },
  { discogs: "Non-Music---Speech", sonaa: null, famille: "Non-Music" },
  { discogs: "Pop---Ballad", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Bollywood", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Bubblegum", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Chanson", sonaa: null, famille: "Pop" },
  { discogs: "Pop---City Pop", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Europop", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Indie Pop", sonaa: null, famille: "Pop" },
  { discogs: "Pop---J-pop", sonaa: null, famille: "Pop" },
  { discogs: "Pop---K-pop", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Kayōkyoku", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Light Music", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Music Hall", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Novelty", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Parody", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Schlager", sonaa: null, famille: "Pop" },
  { discogs: "Pop---Vocal", sonaa: null, famille: "Pop" },
  { discogs: "Reggae---Calypso", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Dancehall", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Dub", sonaa: "dub", famille: "roots" },
  { discogs: "Reggae---Dub Poetry", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Lovers Rock", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Ragga", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Reggae", sonaa: "reggae", famille: "roots" },
  { discogs: "Reggae---Reggae-Pop", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Rocksteady", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Roots Reggae", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Ska", sonaa: null, famille: "Reggae" },
  { discogs: "Reggae---Soca", sonaa: null, famille: "Reggae" },
  { discogs: "Rock---AOR", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Acid Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Acoustic", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Alternative Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Arena Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Art Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Atmospheric Black Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Avantgarde", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Beat", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Black Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Blues Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Brit Pop", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Classic Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Coldwave", sonaa: "coldwave", famille: "industrial" },
  { discogs: "Rock---Country Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Crust", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Death Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Deathcore", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Deathrock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Doo Wop", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Doom Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Dream Pop", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Emo", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Ethereal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Experimental", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Folk Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Folk Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Funeral Doom Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Funk Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Garage Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Glam", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Goregrind", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Goth Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Gothic Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Grindcore", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Grunge", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Hard Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Hardcore", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Heavy Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Indie Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Industrial", sonaa: "industrial", famille: "industrial" },
  { discogs: "Rock---Krautrock", sonaa: "krautrock", famille: "roots" },
  { discogs: "Rock---Lo-Fi", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Lounge", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Math Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Melodic Death Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Melodic Hardcore", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Metalcore", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Mod", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Neofolk", sonaa: null, famille: "Rock" },
  { discogs: "Rock---New Wave", sonaa: null, famille: "Rock" },
  { discogs: "Rock---No Wave", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Noise", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Noisecore", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Nu Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Oi", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Parody", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Pop Punk", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Pop Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Pornogrind", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Post Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Post-Hardcore", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Post-Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Post-Punk", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Power Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Power Pop", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Power Violence", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Prog Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Progressive Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Psychedelic Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Psychobilly", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Pub Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Punk", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Rock & Roll", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Rockabilly", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Shoegaze", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Ska", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Sludge Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Soft Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Southern Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Space Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Speed Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Stoner Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Surf", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Symphonic Rock", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Technical Death Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Thrash", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Twist", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Viking Metal", sonaa: null, famille: "Rock" },
  { discogs: "Rock---Yé-Yé", sonaa: null, famille: "Rock" },
  { discogs: "Stage & Screen---Musical", sonaa: null, famille: "Stage & Screen" },
  { discogs: "Stage & Screen---Score", sonaa: null, famille: "Stage & Screen" },
  { discogs: "Stage & Screen---Soundtrack", sonaa: null, famille: "Stage & Screen" },
  { discogs: "Stage & Screen---Theme", sonaa: null, famille: "Stage & Screen" },];

/* L'acces par etiquette, construit une fois : le modele rend des indices,
   et la page en lit trois par reconnaissance. */
/* LA TABLE SE CHERCHE PAR LE NOM, JAMAIS PAR L'INDEX. L'ordre des lignes
   ci-dessus n'est pas celui des sorties du reseau : cet ordre-la vit dans
   etiquettes-modele.ts, copie de la demonstration dont vient le modele, et
   un test verifie que les deux portent les memes 400 noms. */
const PAR_ETIQUETTE = new Map(STYLES_RECONNUS.map((s) => [s.discogs, s]));

export function styleDeLEtiquette(discogs: string): StyleReconnu | null {
  return PAR_ETIQUETTE.get(discogs) ?? null;
}
